/**
 * The subset of a Pixle Nudge rule that can be represented by source CSS.
 *
 * This intentionally mirrors the persisted shape without importing the
 * client editor. The editor owns its runtime-only Rule type; this module is
 * safe to use from a server route or from a test without a DOM.
 */
export type PixleNudgeRule = {
  sel?: unknown;
  x?: unknown;
  y?: unknown;
  width?: unknown;
  height?: unknown;
  scale?: unknown;
  color?: unknown;
  backgroundColor?: unknown;
  fontFamily?: unknown;
  fontSize?: unknown;
  fontWeight?: unknown;
  lineHeight?: unknown;
  letterSpacing?: unknown;
  text?: unknown;
  textPath?: unknown;
  visible?: unknown;
  locked?: unknown;
  deleted?: unknown;
};

export type PixleNudgeResponsiveScopes = {
  desktop?: unknown;
  base?: unknown;
  tablet?: unknown;
  mobile?: unknown;
  [scope: string]: unknown;
};

export type PixleNudgeStore = {
  version?: unknown;
  pages?: Record<string, unknown>;
  responsive?: Record<string, PixleNudgeResponsiveScopes | unknown>;
  [key: string]: unknown;
};

export type PixleNudgeCssExport = {
  css: string;
  warnings: string[];
  pathname: string;
};

export type RuleLike = PixleNudgeRule;
export type StoreLike = PixleNudgeStore;

type Scope = "base" | "tablet" | "mobile";

const CSS_FILE_HEADER = "/* Generated by Pixle Nudge. */";
const MEDIA_QUERY: Record<Exclude<Scope, "base">, string> = {
  tablet: "@media (max-width: 1024px)",
  mobile: "@media (max-width: 600px)",
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asRule(value: unknown, selector?: string): PixleNudgeRule | null {
  if (!isRecord(value)) return null;
  if (typeof value.sel === "string") return value as PixleNudgeRule;
  if (selector) return { ...value, sel: selector } as PixleNudgeRule;
  return null;
}

/**
 * Accept the persisted array form and a few harmless object forms so an
 * in-progress responsive store can be exported without making this module
 * depend on the editor's implementation details.
 */
function rulesFrom(value: unknown): PixleNudgeRule[] {
  if (Array.isArray(value)) {
    return value
      .map((entry) => asRule(entry))
      .filter((entry): entry is PixleNudgeRule => entry !== null);
  }
  if (!isRecord(value)) return [];

  for (const key of ["rules", "entries", "overrides"]) {
    if (Array.isArray(value[key])) return rulesFrom(value[key]);
  }

  // A responsive scope may be represented as { ".hero": { x: 1, ... } }.
  return Object.entries(value)
    .map(([selector, entry]) => asRule(entry, selector))
    .filter((entry): entry is PixleNudgeRule => entry !== null);
}

function pathRules(store: PixleNudgeStore, pathname: string): PixleNudgeRule[] {
  return rulesFrom(store.pages?.[pathname]);
}

function responsiveRules(
  store: PixleNudgeStore,
  pathname: string,
  scope: "desktop" | "base" | "tablet" | "mobile",
): PixleNudgeRule[] {
  const value = store.responsive?.[pathname];
  if (!isRecord(value)) return [];
  return rulesFrom(value[scope]);
}

function textPathKey(path: unknown): string {
  return Array.isArray(path) && path.every((part) => Number.isInteger(part))
    ? JSON.stringify(path)
    : "-";
}

function ruleKey(rule: PixleNudgeRule): string {
  return `${String(rule.sel)}\u0000${textPathKey(rule.textPath)}`;
}

/**
 * Keep the persisted order for readability, while making duplicate selector /
 * text-node entries deterministic. As with the editor's upsert behavior, the
 * last duplicate value wins.
 */
function dedupeRules(rules: PixleNudgeRule[]): PixleNudgeRule[] {
  const deduped = new Map<string, PixleNudgeRule>();
  for (const rule of rules) {
    const key = ruleKey(rule);
    deduped.set(key, rule);
  }
  return [...deduped.values()];
}

function mergeRules(...groups: PixleNudgeRule[][]): PixleNudgeRule[] {
  return dedupeRules(groups.flat());
}

function numberValue(value: unknown): number | null {
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value === "string" && value.trim() !== "") {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
}

function numberText(value: number): string {
  // Avoid both exponential notation and trailing zeroes in generated CSS.
  return Number.isInteger(value)
    ? String(value)
    : value.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
}

function cssNumber(value: unknown, suffix = ""): string | null {
  const parsed = numberValue(value);
  return parsed === null ? null : `${numberText(parsed)}${suffix}`;
}

function cssDimension(value: unknown): string | null {
  const parsed = numberValue(value);
  if (parsed === null) return null;
  // The editor clamps persisted dimensions to eight design pixels.
  return `${numberText(Math.max(8, parsed))}px`;
}

function safeCssValue(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed || /[;{}\r\n]/.test(trimmed)) return null;
  return trimmed;
}

function safeSelector(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const selector = value.trim();
  if (!selector || /[{}\r\n]/.test(selector)) return null;
  return selector;
}

function selectorLabel(rule: PixleNudgeRule): string {
  const selector = safeSelector(rule.sel) ?? "(invalid selector)";
  const path = textPathKey(rule.textPath);
  return path === "-" ? selector : `${selector} [textPath ${path}]`;
}

function reportNonExportableMetadata(
  rule: PixleNudgeRule,
  warnings: Set<string>,
) {
  if (rule.text !== undefined && rule.text !== null) {
    warnings.add(
      `Text content for ${selectorLabel(rule)} is not exportable to CSS.`,
    );
  }
  if (Object.prototype.hasOwnProperty.call(rule, "locked")) {
    warnings.add(
      `Editor lock state for ${selectorLabel(rule)} is not exportable to CSS.`,
    );
  }
}

function declarationsFor(rule: PixleNudgeRule): string[] {
  const declarations: string[] = [];
  const x = numberValue(rule.x);
  const y = numberValue(rule.y);
  if ((x ?? 0) !== 0 || (y ?? 0) !== 0) {
    declarations.push(
      `translate: ${(x ?? 0) === 0 ? "0" : numberText(x ?? 0)}px ${(y ?? 0) === 0 ? "0" : numberText(y ?? 0)}px !important;`,
    );
  }

  const scale = numberValue(rule.scale);
  if (scale !== null && scale !== 1) {
    declarations.push(`scale: ${numberText(scale)} !important;`);
  }

  const width = cssDimension(rule.width);
  if (width !== null) declarations.push(`width: ${width} !important;`);
  const height = cssDimension(rule.height);
  if (height !== null) declarations.push(`height: ${height} !important;`);

  const color = safeCssValue(rule.color);
  if (color !== null) declarations.push(`color: ${color} !important;`);
  const background = safeCssValue(rule.backgroundColor);
  if (background !== null) {
    declarations.push(`background-color: ${background} !important;`);
  }

  const family = safeCssValue(rule.fontFamily);
  if (family !== null) {
    // Quoting keeps family names such as "Times New Roman" readable and
    // prevents a stored value from changing the declaration grammar.
    declarations.push(`font-family: ${JSON.stringify(family)} !important;`);
  }

  const fontSize = cssNumber(rule.fontSize, "px");
  if (fontSize !== null) declarations.push(`font-size: ${fontSize} !important;`);
  const fontWeight = cssNumber(rule.fontWeight);
  if (fontWeight !== null) {
    declarations.push(`font-weight: ${fontWeight} !important;`);
  }
  const lineHeight = cssNumber(rule.lineHeight, "px");
  if (lineHeight !== null) {
    declarations.push(`line-height: ${lineHeight} !important;`);
  }
  const letterSpacing = cssNumber(rule.letterSpacing, "px");
  if (letterSpacing !== null) {
    declarations.push(`letter-spacing: ${letterSpacing} !important;`);
  }

  if (rule.visible === false || rule.deleted === true) {
    declarations.push("display: none !important;");
  }

  return declarations;
}

function renderRules(
  rules: PixleNudgeRule[],
  warnings: Set<string>,
): string[] {
  const rendered: string[] = [];
  rules.forEach((rule) => reportNonExportableMetadata(rule, warnings));
  for (const rule of dedupeRules(rules)) {
    const selector = safeSelector(rule.sel);
    if (!selector) {
      warnings.add("A Pixle Nudge rule has no valid CSS selector and was skipped.");
      continue;
    }
    const declarations = declarationsFor(rule);
    if (declarations.length === 0) continue;
    rendered.push(
      `${selector} {\n${declarations.map((declaration) => `  ${declaration}`).join("\n")}\n}`,
    );
  }
  return rendered;
}

function renderScope(
  scope: Scope,
  rules: PixleNudgeRule[],
  warnings: Set<string>,
): string {
  const blocks = renderRules(rules, warnings);
  if (blocks.length === 0) return "";
  if (scope === "base") return blocks.join("\n\n");
  const body = blocks.map((block) => block.split("\n").map((line) => `  ${line}`).join("\n")).join("\n\n");
  return `${MEDIA_QUERY[scope]} {\n${body}\n}`;
}

function asStore(value: unknown): PixleNudgeStore {
  return isRecord(value) ? (value as PixleNudgeStore) : {};
}

/**
 * Generate source CSS for one pathname. No filesystem or browser APIs are
 * used here, making this function safe for route handlers and unit tests.
 */
export function exportPixleNudgeCss(
  value: unknown,
  pathname = "/",
): PixleNudgeCssExport {
  const store = asStore(value);
  const warnings = new Set<string>();
  const page = pathRules(store, pathname);
  const base = responsiveRules(store, pathname, "base");
  const desktop = responsiveRules(store, pathname, "desktop");
  const tablet = responsiveRules(store, pathname, "tablet");
  const mobile = responsiveRules(store, pathname, "mobile");
  [...page, ...base, ...desktop, ...tablet, ...mobile].forEach((rule) =>
    reportNonExportableMetadata(rule, warnings),
  );
  const desktopRules = mergeRules(
    page,
    base,
    desktop,
  );

  const scopes = [
    renderScope("base", desktopRules, warnings),
    renderScope("tablet", tablet, warnings),
    renderScope("mobile", mobile, warnings),
  ].filter(Boolean);
  const css = scopes.length > 0 ? `${CSS_FILE_HEADER}\n\n${scopes.join("\n\n")}\n` : "";

  return {
    css,
    warnings: [...warnings].sort(),
    pathname,
  };
}

// Named aliases keep the small utility convenient for callers that describe
// the operation as generation rather than export.
export const generatePixleNudgeCss = exportPixleNudgeCss;
export const exportRulesToCss = exportPixleNudgeCss;
